### ISSUE TITLE
Move Azure template feeds from microsoft/typespec

### ISSUE THREAD

**Issue by markcowl** [Azure/typespec-azure#10]
Now that this repo is public, we should move the Azure feeds here from eng/feeds in the microsoft/typespec repo.

- [x] Copy feeds to this repo
- [x] Update doc and aka links that point to microsoft/typespec
- [x] Remove the feeds from microsoft/typespec

**Comment by markcowl** [comment]
est: 1
