### ISSUE TITLE
Spread is spread (parameters)

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#1043]
### Clear and concise description of the problem

We no longer want to recover a model from spread by default. The current behavior creates a complicated story for spreading, and leads to confusing emitter logic. The following needs to be done in this order

1. [x] [Decorate brownfield services with @bodyRoot ](https://github.com/Azure/azure-rest-api-specs/issues/29504)
2. [x] [Update emitter logic](https://github.com/Azure/typespec-azure/issues/772)
3. [x] [Add `overrideClientMethod` decorator](https://github.com/Azure/typespec-azure/issues/1054)
4. [ ] [Move vendored `BodyParameter` to core](https://github.com/Azure/typespec-azure/issues/1042)

The final step is not required for the story to be complete, I'm only linking it in this issue as a reference.

Down the line, we also want to look into clearing up the [logic in responses too](https://github.com/Azure/typespec-azure/issues/1044). We will wait for a traits redesign first.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by weidongxu-microsoft** [comment]
typespec-java 0.18.0 released with this logic

**Comment by iscai-msft** [comment]
Closing because all of the tcgc work has been completed with the introduction of the `@override` decorator
