### ISSUE TITLE
Migrate language's emitter to Microsoft/Typespec

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1267]
```[tasklist]
### Implementation
- [ ] https://github.com/Azure/autorest.python/issues/2733
- [ ] https://github.com/Azure/autorest.typescript/issues/2609
- [ ] https://github.com/Azure/autorest.typescript/issues/2608
- [ ] https://github.com/Azure/autorest.csharp/issues/4947
- [ ] https://github.com/Azure/autorest.java/issues/2883
```
