### ISSUE TITLE
Support AllowReserved in Path

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#1318]
```[tasklist]
### TypeSpec
- [ ] https://github.com/microsoft/typespec/issues/3736
```

```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/665
- [ ] https://github.com/Azure/typespec-azure/issues/1316
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/1317
- [ ] https://github.com/Azure/autorest.python/issues/2754
- [ ] https://github.com/Azure/autorest.java/issues/2896
- [ ] https://github.com/Azure/autorest.typescript/issues/2734
- [ ] https://github.com/Azure/autorest.csharp/issues/4966
- [ ] https://github.com/Azure/autorest.go/issues/1422
- [ ] https://github.com/Azure/autorest.cpp/issues/373
- [ ] https://github.com/Azure/autorest.rust/issues/82
```

**Comment by tadelesh** [comment]
also this feature could cover:
```
@route("/{+scope}/action") op action(scope: string): void;
```
