### ISSUE TITLE
Namespace refactoring

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#1724]
```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/758
- [ ] https://github.com/Azure/typespec-azure/issues/1722
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/1723
- [ ] https://github.com/Azure/autorest.java/issues/2968
- [ ] https://github.com/Azure/autorest.typescript/issues/2877
- [ ] https://github.com/Azure/autorest.csharp/issues/5124
- [ ] https://github.com/Azure/autorest.go/issues/1452
- [ ] https://github.com/Azure/autorest.cpp/issues/404
- [ ] https://github.com/Azure/typespec-rust/issues/130
- [ ] https://github.com/Azure/autorest.python/issues/2795
```

**Comment by lmazuel** [comment]
Dup of https://github.com/microsoft/typespec/issues/4537
