### ISSUE TITLE
ClientInitialization/ParamAlias

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#1768]
```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/766
- [ ] https://github.com/Azure/typespec-azure/issues/1766
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/1767
- [ ] https://github.com/Azure/autorest.python/issues/2894
- [ ] https://github.com/Azure/autorest.java/issues/2972
- [ ] https://github.com/Azure/autorest.typescript/issues/2887
- [ ] https://github.com/Azure/autorest.csharp/issues/5131
- [ ] https://github.com/Azure/autorest.go/issues/1458
- [ ] https://github.com/Azure/autorest.cpp/issues/412
- [ ] https://github.com/Azure/typespec-rust/issues/137
```
