### ISSUE TITLE
Migrate swagger to TypeSpec for brownfield service

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#1850]
### Exit Criterion

**Long term**
1. Functional equivalent TypeSpec
2. Functional equivalent SDK from TypeSpec without breaking change

**Short term**
1. Functional equivalent TypeSpec
2. Functional equivalent SDK from swagger generated from TypeSpec without breaking change

### Feature gap for Compute
Compute is where our current effort is, which has high priority.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/typespec-azure/issues/1849
- [ ] https://github.com/Azure/typespec-azure/issues/234
- [ ] https://github.com/Azure/typespec-azure/issues/1844
- [ ] [Place holder] Parameter order
- [ ] https://github.com/Azure/typespec-azure/issues/1845
- [ ] https://github.com/Azure/typespec-azure/issues/1846
- [ ] https://github.com/Azure/typespec-azure/issues/1847
- [ ] https://github.com/Azure/typespec-azure/issues/1848
``` 

### Converter gap
For compute, we are now converting manually. But all these efforts should be integrated into converter so that following services could do automatically.
