### ISSUE TITLE
[Documentation]:  Improve docs for dataplane code generation for more supported features 

### ISSUE THREAD

**Issue by lirenhe** [Azure/typespec-azure#245]
Please describe the issue or feature request.

Current site https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/00howtogen lack some detailed information on how the generated SDK would look like for various TypeSpec input.

**Describe your ideas for solutions**
We need to improve the DPG documentation to ensure all our partners would understand the expected SDK would look like for their TypeSpec inputs.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/typespec-azure/issues/1347
- [x] The spread of alias & models
- [ ] https://github.com/Azure/typespec-azure/issues/1351
- [ ] https://github.com/Azure/typespec-azure/issues/1348
- [ ] https://github.com/Azure/typespec-azure/issues/1349
```

**Comment by lirenhe** [comment]
Created a couple of sub issues for each feature that need documentation.  Feel free to add more into this list.

**Comment by iscai-msft** [comment]
All listed docs have been added, closing
