### ISSUE TITLE
[Epic] `@projectedName` migration

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#266]
Issue for managing the projectedname migration

```[tasklist]
### Tasks
- [x] Add `@clientName`
- [x] Add `@encodedName`
- [x] Migrate `@projectedName("json"` -> `@encodedName("json"`
- [x] Csharp emitter support https://github.com/Azure/autorest.csharp/issues/4168
- [x] Check migration for RPSaasMaster -> no `@projectedName`
- [x] Migrate `@projectedName("client"` -> `@clientname` @iscai-msft https://github.com/Azure/azure-rest-api-specs/pull/27797/files
- [x] Deprecate `@projectedName` [Ready]
- [x] Update swagger converter to not use `@projectedName` https://github.com/Azure/autorest/issues/4884
- [x] Update any docs
- [ ] https://github.com/Azure/typespec-azure/issues/265
```

**Comment by timotheeguerin** [comment]
This is done, only remaining items is fixing any new violations until the next release
