### ISSUE TITLE
[Dt]: [Epic]: Convert open enumerations to unions

### ISSUE THREAD

**Issue by markcowl** [Azure/typespec-azure#269]
```[tasklist]
### Tasks
- [x] [Laurent]: Convert data-plane specs in azure-rest-api-specs/main
- [x] [Tim] Add union for open enum rule to Azure.Core all ruleset https://github.com/Azure/typespec-azure/pull/467
- [ ] https://github.com/Azure/typespec-azure/pull/505
- [ ] https://github.com/Azure/typespec-azure/pull/459
- [ ] https://github.com/Azure/typespec-azure/pull/500
- [ ] https://github.com/Azure/typespec-azure/pull/506
- [x] [TypeSpec]: Convert enums to unions for library types (Azure.Core, Azure.ResourceManager)
- [ ] https://github.com/Azure/typespec-azure/pull/473
- [ ] https://github.com/Azure/typespec-azure/issues/97
- [ ] https://github.com/Azure/typespec-azure/pull/707
- [ ] https://github.com/Azure/typespec-azure/pull/706
- [ ] [TypeSpec] Deprecate `@fixed`
```
