### ISSUE TITLE
[Epic/Design]: Identify and fix or remove Swagger Breaking Change Rules for TypeSpec specs

### ISSUE THREAD

**Issue by markcowl** [Azure/typespec-azure#36]
related to: https://github.com/Azure/typespec-azure/issues/35

- Many breaking change rules apply to the names of elements of the spec that do not impact the API on the wire, but do impact client generation.  Need a way to reflect a change in client name in a way that turnes off these rules
  - DPG decorators used in swagger generation (e.g. x-ms-client-name)
  - Linting rules are altered to be aware of x-ms-client-name in areas where they are not
  - Alternately, DPG decorators add suppressions for breaking change rules (where inline suppressions are allowed)
- Other breaking change rules are irrelevant and should be removed
  - MissingParameters mistakenly marking method parameters not appearing in the global parameters section
  - PUT/PATCH violations for PATCH model not including mutability

**Comment by markcowl** [comment]
- [ ] 1007 - RemovedClientParameter : This error routinely flags false positives, in which global parameters (or path parameters) are replaced with operation parameters - these are equivalent as long as their names and properties match and they are not marked as 'client' parameters
- [ ] 1021 - AddedAdditionalProperties: This rule should treat schemas with `type: object`, schemas with `type: object, additionalProperties: true` and schemas with `type:object, additionalPropeties: {}` as all equivalent.
- [ ] 1023 - TypeFormatChanged: This rule should exempt paging 'nextLink' properties from the check - since these are non-public types, there is no breaking change implied
- [ ] 1025 - RequiredStatusChange: This rule should exempt 'value' and 'nextLink' properties in paging types
- [ ] 1034 - AddedRequiredProperty: This rule should exempt 'value' and 'nextLink' properties in paging types
- [ ] 1042 - ChangedParameterOrder: This rule should not include the order of ApiVersion parameter as part of the calculation - it does not matter where this specialized parameter occurs in the parameter order.  It also should handle the ordering of path parameters when compared to method parameters.
