### ISSUE TITLE
[Dt]: TypeSpec Telemetry/KPI collection and tools

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#463]
- [ ] PR using TSP
- [ ] RP adopted TSP at rest in repos
- [x] TypeSpec.io web analytics
- [ ] ARM review time improvements
