### ISSUE TITLE
[Dt]: Support 1P teams to adopt TypeSpec and extend libraries, emitters

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#466]
- [x] CLI TypeSpec emitter
- [x] PSH TypeSpec emitter
- [x] Portal TypeSpec emitter
- [ ] Bicep TypeSpec emitter
- [x] Continoued Liftr support

**Comment by allenjzhang** [comment]
As each team is working on their emitter directly, TypeSpec team will provide technical support and if any bug fixes.
