### ISSUE TITLE
[Dt] Documentation Improvements

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#479]
- [ ] Re-organize TypeSpec Azure document site
- [ ] Improve Conversion Page to capture exapandable targeted sections such as Breaking Change, LintDiff, and conversion patterns
- [ ] Include Sample / Scenarios on site and playground
- [ ] [Dependency](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1993304) Improve Day 0 experience
- [ ] TypeSpec `rest-api-spec` repo video tutorial
- [ ] TypeSpec langage video tutorial
- [ ] TypeSpec ARM video tutorial
