### ISSUE TITLE
Implement TCGC's SdkPackage types

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#594]
```[tasklist]
### Implement TCGC's SdkPackage types
- [x] https://github.com/Azure/autorest.python/issues/2485
- [ ] https://github.com/Azure/autorest.typescript/issues/2406
- [ ] https://github.com/Azure/autorest.csharp/issues/4534
- [ ] https://github.com/Azure/autorest.go/issues/1186
- [ ] https://github.com/Azure/autorest.typescript/issues/2408
- [ ] https://github.com/Azure/autorest.cpp/issues/346
- [ ] https://github.com/Azure/autorest.rust/issues/6
- [ ] https://github.com/Azure/autorest.java/issues/2665
```
