### ISSUE TITLE
Multipart Form Data

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#609]
```[tasklist]
### TypeSpec
- [ ] https://github.com/microsoft/typespec/issues/3046
```

```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/548
- [ ] https://github.com/Azure/typespec-azure/issues/607
- [ ] https://github.com/Azure/autorest.python/issues/2488
- [ ] https://github.com/Azure/autorest.java/issues/2668
- [ ] https://github.com/Azure/autorest.typescript/issues/2411
- [ ] https://github.com/Azure/autorest.csharp/issues/4540
- [ ] https://github.com/Azure/autorest.typescript/issues/2423
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/608
- [ ] https://github.com/Azure/autorest.python/issues/2489
- [ ] https://github.com/Azure/autorest.java/issues/2669
- [ ] https://github.com/Azure/autorest.typescript/issues/2412
- [ ] https://github.com/Azure/autorest.csharp/issues/4541
- [ ] https://github.com/Azure/autorest.typescript/issues/2422
```
