### ISSUE TITLE
Method signature (alias / spread)

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#612]
```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/549
- [ ] https://github.com/Azure/typespec-azure/issues/610
- [ ] https://github.com/Azure/autorest.python/issues/2490
- [ ] https://github.com/Azure/autorest.java/issues/2670
- [ ] https://github.com/Azure/autorest.typescript/issues/2413
- [ ] https://github.com/Azure/autorest.csharp/issues/4542
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/611
- [ ] https://github.com/Azure/autorest.python/issues/2491
- [ ] https://github.com/Azure/autorest.java/issues/2671
- [ ] https://github.com/Azure/autorest.typescript/issues/2414
- [ ] https://github.com/Azure/autorest.csharp/issues/4543
```
