### ISSUE TITLE
Streaming/SSE

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#615]
```[tasklist]
### TypeSpec
- [ ] https://github.com/microsoft/typespec/issues/2378
```

```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/550
- [ ] https://github.com/Azure/typespec-azure/issues/613
- [ ] https://github.com/Azure/autorest.python/issues/2492
- [ ] https://github.com/Azure/autorest.java/issues/2672
- [ ] https://github.com/Azure/autorest.typescript/issues/2415
- [ ] https://github.com/Azure/autorest.csharp/issues/4544
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/614
- [ ] https://github.com/Azure/autorest.python/issues/2493
- [ ] https://github.com/Azure/autorest.java/issues/2673
- [ ] https://github.com/Azure/autorest.typescript/issues/2416
- [ ] https://github.com/Azure/autorest.csharp/issues/4545
```
