### ISSUE TITLE
Visibility

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#618]
```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/551
- [ ] https://github.com/Azure/typespec-azure/issues/616
- [ ] https://github.com/Azure/autorest.python/issues/2494
- [ ] https://github.com/Azure/autorest.java/issues/2674
- [ ] https://github.com/Azure/autorest.typescript/issues/2417
- [ ] https://github.com/Azure/autorest.csharp/issues/4546
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/617
- [ ] https://github.com/Azure/autorest.python/issues/2495
- [ ] https://github.com/Azure/autorest.java/issues/2675
- [ ] https://github.com/Azure/autorest.typescript/issues/2418
- [ ] https://github.com/Azure/autorest.csharp/issues/4547
```
