### ISSUE TITLE
Flattening support

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#622]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/typespec-azure/issues/633
- [ ] https://github.com/Azure/autorest.csharp/issues/4040
- [ ] https://github.com/Azure/autorest.java/issues/2460
- [ ] https://github.com/Azure/autorest.python/issues/2187
- [ ] https://github.com/Azure/autorest.typescript/issues/2164
- [ ] https://github.com/Azure/typespec-azure/issues/13
- [ ] https://github.com/Azure/cadl-ranch/issues/471
- [ ] https://github.com/Azure/autorest.go/issues/1194
- [ ] https://github.com/Azure/autorest.rust/issues/2
- [ ] https://github.com/Azure/autorest.cpp/issues/342
```
