### ISSUE TITLE
Basic versionning

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#646]
This is about following the basic guidelines for SDK: the constructor must have a way to change the API version.
This issue is not about any decorators from TypeSpec and versionning, like `@add`. No client side validation is expected.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/cadl-ranch/issues/554
- [ ] https://github.com/Azure/autorest.typescript/issues/2427
- [ ] https://github.com/Azure/autorest.csharp/issues/4559
- [ ] https://github.com/Azure/autorest.java/issues/2680
- [ ] https://github.com/Azure/autorest.python/issues/2503
```
