### ISSUE TITLE
Add new ruleset package for spec repo

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#654]
```[tasklist]
### Tasks
- [x] Implement new package
- [x] Merge and release new package
- [x] Update TypeSpec validation to enforce new ruleset names
- [x] Bulk migrate all specs to new ruleset
```

**Comment by markcowl** [comment]
est: 5
pri: 2
