### ISSUE TITLE
Remove dependency on OpenAPI for Arm Specs

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#687]
### Clear and concise description of the problem

Right now, the ARM library depends on `typespec-autorest`, I believe only for their `@extension` headers. This creates issues because`tcgc` can not test ARM code because `typespec-autorest` depends on `tcgc`. Additionally, we should also be moving away from the `@extension` decorator.

I've taken the liberty to compile a list of the extensions I see in use in the main branch of `azure-rest-api-specs`

- [x] `x-ms-azure-resource`
- [x] `x-ms-identifiers`
- [x] ~`x-ms-client-flatten`~ use `@azure-tools/typespec-client-generator-core`'s `@flattenProperty` instead
- [x] ~`x-ms-long-running-operation`~ use LRO framework instead in `azure-core`
- [x] ~`x-ms-long-running-operation-options`~ use LRO framework instead in `azure-core`
- [ ] Remove ad-hoc usage of openapi decorators in specs

### Tasks
- [x] https://github.com/Azure/typespec-azure/issues/697
- [x] `x-ms-azure-resource`
- [x] https://github.com/Azure/typespec-azure/issues/1473
- [x] ~`x-ms-client-flatten`~ use `@azure-tools/typespec-client-generator-core`'s `@flattenProperty` instead
- [x] ~`x-ms-long-running-operation`~ use LRO framework instead in `azure-core`
- [x] ~`x-ms-long-running-operation-options`~ use LRO framework instead in `azure-core`
