### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#705]
```[tasklist]
### TypeSpec
- [ ] https://github.com/microsoft/typespec/issues/3197
```

```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/561
- [ ] https://github.com/Azure/typespec-azure/issues/703
- [ ] https://github.com/Azure/autorest.python/issues/2534
- [ ] https://github.com/Azure/autorest.java/issues/2714
- [ ] https://github.com/Azure/autorest.typescript/issues/2460
- [ ] https://github.com/Azure/autorest.csharp/issues/4608
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/704
- [ ] https://github.com/Azure/autorest.python/issues/2535
- [ ] https://github.com/Azure/autorest.java/issues/2715
- [ ] https://github.com/Azure/autorest.typescript/issues/2461
- [ ] https://github.com/Azure/autorest.csharp/issues/4609
```

**Comment by weidongxu-microsoft** [comment]
last gap in java
- https://github.com/microsoft/typespec/issues/11306
