### ISSUE TITLE
Projected version support

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#718]
With TCGC `0.41.4`, we only generate the surface area for the latest API version. If a spec generator doesn't want this behavior, they will have to add `api-version: all` to their `tspconfig.yaml`. TCGC handles all of this code for you, so you don't need to do anything besides update your tcgc version

```[tasklist]
### TypeSpec
- [ ] https://github.com/microsoft/typespec/issues/3204
```

```[tasklist]
### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/564
- [ ] https://github.com/Azure/typespec-azure/issues/716
```

```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/717
- [ ] https://github.com/Azure/autorest.python/issues/2539
- [ ] https://github.com/Azure/autorest.java/issues/2716
- [ ] https://github.com/Azure/autorest.typescript/issues/2467
- [ ] https://github.com/Azure/autorest.csharp/issues/4618
- [ ] https://github.com/Azure/autorest.go/issues/1303
- [ ] https://github.com/Azure/autorest.cpp/issues/350
- [ ] https://github.com/Azure/autorest.rust/issues/9
```
