### ISSUE TITLE
 Contribute to the Swagger-to-TypeSpec Converter for Mgmt. Plane APIs

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/typespec-azure#72]
**TSP tasks**

TSP syntax could not express some of the ARM usages, and this part needs fix from TSP.

```[tasklist]
# TSP tasks
- [ ] https://github.com/Azure/typespec-azure/issues/55
- [ ] https://github.com/Azure/typespec-azure/issues/56
- [ ] https://github.com/Azure/typespec-azure/issues/59
- [ ] https://github.com/Azure/typespec-azure/issues/62
- [ ] https://github.com/Azure/typespec-azure/issues/63
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3761
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3764
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3765
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3774
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3775
- [ ] https://github.com/microsoft/typespec/issues/2442
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3675
- [ ] https://github.com/Azure/typespec-azure/issues/103
- [ ] https://github.com/Azure/typespec-azure/issues/104
- [ ] https://github.com/Azure/typespec-azure/issues/105
- [ ] https://github.com/Azure/typespec-azure/issues/37
- [ ] https://github.com/Azure/typespec-azure/issues/130
- [ ] https://github.com/Azure/typespec-azure/issues/131
- [ ] https://github.com/Azure/typespec-azure/issues/132
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3763
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3739
```

**Converter tasks**
Converter tool issues / tasks.

```[tasklist]
# Converter tasks
- [ ] https://github.com/Azure/autorest/issues/4858
- [ ] https://github.com/Azure/autorest/issues/4857
- [ ] https://github.com/Azure/autorest/issues/4787
- [ ] https://github.com/Azure/autorest/issues/4788
- [ ] https://github.com/Azure/autorest/issues/4791
- [ ] https://github.com/Azure/autorest/issues/4795
- [ ] https://github.com/Azure/autorest/issues/4847
- [ ] https://github.com/Azure/autorest/issues/4832
- [ ] https://github.com/Azure/autorest/issues/4850
- [ ] https://github.com/Azure/autorest/issues/4848
- [ ] https://github.com/Azure/autorest/issues/4859
- [ ] https://github.com/Azure/typespec-azure/issues/123
- [ ] https://github.com/Azure/autorest/issues/4861
```

**Other tasks**
Some will be resolved by converter, some need TSP support, need feature investigation.

```[tasklist]
# Other tasks
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3760
- [ ] https://github.com/Azure/typespec-azure-pr/issues/3775
- [ ] https://github.com/Azure/typespec-azure/issues/60
- [ ] https://github.com/Azure/typespec-azure/issues/106
- [ ] https://github.com/Azure/typespec-azure/issues/310
```

**RPs in conversion**
https://github.com/Azure/typespec-azure/issues/78

**Related links**
- https://github.com/Azure/autorest/issues?page=1&q=is%3Aissue+is%3Aopen+label%3Aopenapi-to-tsp
- https://github.com/Azure/typespec-azure/issues?q=is%3Aopen+is%3Aissue+label%3A%22Swagger+Converter%22
- https://github.com/Azure/typespec-azure-pr/issues?q=is%3Aopen+is%3Aissue+label%3A%22Swagger+Converter%22
