### ISSUE TITLE
[tcgc] clean up before stable

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#835]
```[tasklist]
### Tasks
- [ ] Consolidating some of the build in types: url vs uri, uuid vs guid
- [ ] Revisit the type system in TCGC
- [ ] Make Azure part extend from non-branding part of TCGC
```

**Comment by iscai-msft** [comment]
we've already released so I'm going to o ahead and close because we have separate issues for each of these
