### ISSUE TITLE
[EPIC] Consolidate the TypeSpec onboarding process for Mgmt. plane

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/typespec-azure#952]
For the long term, the TypeSpec review should be handled by the Arm team. However, before that, we need to complete the following tasks:

- [ ] Fix all mgmt. plane related TypeSpec issues
- [ ] Prepare the document for TypeSpec migration
- [ ] Prepare the document for TypeSpec review
- [ ] EngSys ready that can catch TypeSpec issues
- [ ] Launch training courses for Arm
- [ ] Help on reviewing and fixing TypeSpec for service team before Arm team can take over the review
