### ISSUE TITLE
Sample generation

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#975]
```[tasklist]
### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/974
- [ ] https://github.com/Azure/autorest.python/issues/2622
- [ ] https://github.com/Azure/autorest.java/issues/2808
- [ ] https://github.com/Azure/autorest.typescript/issues/2562
- [ ] https://github.com/Azure/autorest.csharp/issues/4805
- [ ] https://github.com/Azure/autorest.go/issues/1375
- [ ] https://github.com/Azure/autorest.cpp/issues/361
- [ ] https://github.com/Azure/autorest.rust/issues/33
```
